#!/usr/bin/env bash
#Process and PID file
echo '$$' > /var/run/myscript.pid

while :
do        
	echo "To infinity and beyond"
	sleep 2		
	
	trap "echo I hate the kill command; rm /var/run/myscript.pid; exit" SIGTERM
	trap "echo Y U love me ?!; exit" SIGINT	
	trap "rm /var/run/myscript.pid; exit" SIGQUIT || SIGTERM
done
