#!/usr/bin/env bash
#"10. Manage my process"

case $1 in 	
	start)
		./manage_my_process & echo "$!" > /var/run/my_process.pid
		echo 'manage_my_process started'
		;;
	stop)
	      kill $(less /var/run/my_process.pid)
	      rm /var/run/my_process.pid
              echo "manage_my_process stopped"
	      ;;
	restart) 
		kill $(less /var/run/my_process.pid)	
		rm /var/run/my_process.pid
		manage_my_process & echo "$!" > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac

